FROM node:lts-alpine

WORKDIR /app

# FFmpeg is required for video transcoding
RUN apk add --no-cache ffmpeg

COPY package*.json ./

RUN npm ci

COPY . .

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

# Generate Prisma Client
RUN npx prisma generate

# Build TypeScript
RUN npm run build

CMD ["node", "dist/workers/video-processing.worker.js"]